### ISSUE TITLE
Wrong firmware partition size in RT5350F-OLINUXINO.dts

### ISSUE THREAD

**Issue by samueleforconi** [OLIMEX/openwrt#1]
In file RT5350F-OLINUXINO.dts, the "firmware" partition size should be changed from 0x3b0000 to 0x7b0000 to use the entire 8MB flash of the Olinuxino RT5350F.

I also suggest to add the i2c declaration in the palmbus@10000000 section:
i2c@900 { 
    status = "okay";
};

**Comment by selfbg** [comment]
We fixed this issue in the latest sources. 

Thank you for the support.

**Comment by tgeorgebogdan** [comment]
hello,
i'm trying to build openwrt but it seems that it can't download:

--2015-07-15 05:35:30--  http://downloads.openwrt.org/sources/mtd-utils-1.5.1-92686f212c9a4e16891c6a3c57629cbf4f0f8360.tar.gz
Resolving downloads.openwrt.org (downloads.openwrt.org)... 78.24.191.177
Connecting to downloads.openwrt.org (downloads.openwrt.org)|78.24.191.177|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-15 05:35:31 ERROR 404: Not Found.

Download failed.
No more mirrors to try - giving up.
Checking out files from the git repository...
Cloning into 'mtd-utils-1.5.1'...
fatal: unable to connect to git.infradead.org:
git.infradead.org[0: 198.137.202.9]: errno=Connection refused
git.infradead.org[1: 2001:1868:205::9]: errno=Network is unreachable

Can you help me?

**Comment by hehopmajieh** [comment]
Do you update feeds ?

./scripts/feeds update -a
./scripts/feeds install -a
if the problem persists try to change mtd-utils download location from appropriate Make-file.
p.s Please do not open closed issues that not involving your problem
~Best
