### ISSUE TITLE
No file system support is included nor can be installed

### ISSUE THREAD

**Issue by blinkenlight** [OLIMEX/openwrt#3]
The 'kmod-fs-ext4' package (vital if one wants to mount an ext4 USB drive) that was included in previous pre-compiled images seems to be missing in the latest binary. Unfortunately, it seems that it cannot be installed either, because the one in the configured repository depends on kernel version '3.18.17-1-73d2b013e81727fe0664fd1b78bd291e' while the kernel of the binary image is the newer 3.18.19...

**Comment by selfbg** [comment]
We just fixed that. Now ext4 support is in the kernel image.
You can download the latest image from here:
https://github.com/OLIMEX/OLINUXINO/tree/master/SOFTWARE/RT5350F/Prebuilt%20images
