### ISSUE TITLE
out of space on the rt5350f after upgrade of chaos calmer 15.05.1

### ISSUE THREAD

**Issue by ebdavide** [OLIMEX/openwrt#5]
I have just updated the firmware of my rt5350f to the last release of chaos calmer 
https://downloads.openwrt.org/chaos_calmer/15.05.1/ramips/rt305x/openwrt-15.05.1-ramips-rt305x-olinuxino-rt5350f-squashfs-sysupgrade.bin
After having finished the installation via tftp I noticed that the free space is now just 232 KB, while it was 2 MB with the previous version. Is there any module or packet that has been added and that I can remove. Do you think I did something wrong?

On the current version of chaos calmer 15.05.1 when I type df -h I obtain:

> root@OpenWrt:~# df -h
> Filesystem Size Used Available Use% Mounted on
> rootfs 448.0K 216.0K 232.0K 48% /
> /dev/root 2.3M 2.3M 0 100% /rom
> tmpfs 14.2M 624.0K 13.6M 4% /tmp
> tmpfs 14.2M 48.0K 14.2M 0% /tmp/root
> tmpfs 512.0K 0 512.0K 0% /dev
> /dev/mtdblock6 448.0K 216.0K 232.0K 48% /overlay
> overlayfs:/overlay 448.0K 216.0K 232.0K 48% /

On the previous version instead:

> root@OpenWrt:/# df -h
> Filesystem Size Used Available Use% Mounted on
> rootfs 4.2M 2.1M 2.1M 50% /
> /dev/root 2.5M 2.5M 0 100% /rom
> tmpfs 14.3M 432.0K 13.8M 3% /tmp
> /dev/mtdblock6 4.2M 2.1M 2.1M 50% /overlay
> overlayfs:/overlay 4.2M 2.1M 2.1M 50% /
> tmpfs 512.0K 0 512.0K 0% /dev

**Comment by DanKoloff** [comment]
It seems like the partition size set in RT5350F-OLINUXINO.dts is incorrect. Check here: [partition size issue](https://github.com/OLIMEX/openwrt/issues/1)

“

In RT5350F-OLINUXINO.dts, the "firmware" partition size should be changed from 0x3b0000 to 0x7b0000 to use the entire 8MB flash of the Olinuxino RT5350F.

“

Best regards,
Lub/OLIMEX

**Comment by ebdavide** [comment]
The 2 olinuxino dts files have already been changed to "0x7b0000".

**Comment by ebdavide** [comment]
Can I change the device tree source without recompiling openwrt? I cannot find the dts files of chaos calmer 15.05.1
